### Get currencies - 200 OK
GET http://localhost:8080/currency_conversion/currencies
Accept: application/json
Content-Type: application/json


### Add new currency - 409 Conflict
### Currency with code: 'USD' already exists
POST http://localhost:8080/currency_conversion/currencies
Accept: application/json
Content-Type: application/x-www-form-urlencoded

name = US Dollar &
code = USD &
sign = $

### Add new currency - 400 Bad Request
### Missing parameter - code
POST http://localhost:8080/currency_conversion/currencies
Accept: application/json
Content-Type: application/x-www-form-urlencoded

name = Argentine Peso &
code =  &
sign = $

### Add new currency - 201
POST http://localhost:8080/currency_conversion/currencies
Accept: application/json
Content-Type: application/x-www-form-urlencoded

name = Argentine Peso &
code = ARS &
sign = $